Document: whatsup
Title: Debian whatsup Manual
Author: <insert document author here>
Abstract: This manual describes what whatsup is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/whatsup/whatsup.sgml.gz

Format: postscript
Files: /usr/share/doc/whatsup/whatsup.ps.gz

Format: text
Files: /usr/share/doc/whatsup/whatsup.text.gz

Format: HTML
Index: /usr/share/doc/whatsup/html/index.html
Files: /usr/share/doc/whatsup/html/*.html

  
